### ISSUE TITLE
T2P - Python-Script in ein extra Service auslagern

### ISSUE THREAD

**Issue by Jannik-Steck** [tfreytag/WoPeD#113]
Python-Script in einen eigenen Service auslagern und über HTTP-Befehle aufrufen und die Informationen austauschen.

Aufgabe des Python-Scripts:
--> Workaround um eine aktuellere Parser-Version verwenden zu können

- [x] Der Python-Script als eigenen Service erstellen.
- [x] Das Dockerfile erstellen und korrekt ausführen.

**Comment by harunby** [comment]
aufzufinden unter: https://github.com/harunby/TreeGenerator

**Comment by jonastrautmann** [comment]
Python Skript erstellt und ausgelagert durch @harunby
