### ISSUE TITLE
BPMN XML String

### ISSUE THREAD

**Issue by jonastrautmann** [tfreytag/WoPeD#119]
Hier wird auf Antwort durch Tom Thaler gewartet:
- [x] User-Story 1.: String aus dem WorldModel erstellen
- [x] User-Story 2: erstelleten String umwandeln zu XML String der dann im Folgeschritt interpretiert werden kann

**Comment by tfreytag** [comment]
Der Code von Tom Thaler ist mittlerweile aufgetaucht, als alter Branch in unserem Repository. Herr Kanzler hat sich das schon angeschaut, sie sollten sich mit ihm synchronisieren.

**Comment by jonastrautmann** [comment]
Wurde aus altem WoPeD Stand extrahiert und implementiert in Zusammenarbeit mit @KanBen86
