### ISSUE TITLE
Installer für MacOS

### ISSUE THREAD

**Issue by NilsLeger** [tfreytag/WoPeD#67]
App Ordner erzeugen wie in WoPeD auf SourceForge (mit doc, Changelog etc.)

**Comment by ChelloX** [comment]
@NilsLeger Issue kann geschlossen werden, oder?

**Comment by NilsLeger** [comment]
> @NilsLeger Issue kann geschlossen werden, oder?

Ja, der funktioniert. Ich schließe den Issue.
