### ISSUE TITLE
T2P - Nebentasks

### ISSUE THREAD

**Issue by jonastrautmann** [tfreytag/WoPeD#90]
Dieses Issues beinhaltet Nebentasks die sich in kein konkreteres Issue einteilen liesen. Mit der Erfüllung dieser Tasks wird WoPeD für den Anwender ansehnlicher.

- [x] User-Story 1.: Als Nutzer von WoPeD möcht ich, dass ein aussagekräftiger Fehler erscheint, sollte WoPeD den eingegebenen Text nicht richtig interpretieren können (z.B. bei einer Eingabe von deutschem Text)
![grafik](https://user-images.githubusercontent.com/46446573/105504053-9ac85680-5cc7-11eb-9f35-8da7aa2091f5.png)
- [x] User-Story 2.:  Als Entwickler von WoPeD möchte ich, dass der T2P Algorithmus refactored wird.

**Comment by Jannik-Steck** [comment]
Die User-Story mit der Schleifen-Thematik aus dem Epic (Kontrollflussstrukturen verbessern) wird in das Epic (Nebentasks) geschoben. Absprache mit Benjamin am 17. Mai 2021

**Comment by jonastrautmann** [comment]
Nach Absprache mit Herrn Freytag ist die User Story zum beibehalten des eingegeben Textes in WoPeD bereits so wie geplant (hier gab es bei der Erstellung ein Missverständnis)

**Comment by jonastrautmann** [comment]
Anpassung der Fehlernachricht durch @jonastrautmann und refactoring durch @Jannik-Steck

**Comment by Jannik-Steck** [comment]
Information zu dem Epic: 

Aufgrund der höheren Priorität des Epics "BPMN" konnten leider die beiden letzten User-Stories nicht durchgeführt werden.
- User-Story.: Als Nutzer von WoPed möchte ich, dass Transitions die mit boolschen Attributen versehen wurden (time-triggered und message-triggered) in der zum Prozessmodell gehörenden XML aufgezeigt werden.
- User-Story.: Anzeige eines Loading Spinners während das Prozessmodell erstellt wird im WoPeD Client
